@echo off
echo Building COSINE CLI...
:: Build the executable from the project root, using the source in ./cmd/cosine-cli
go build -o cosine-cli.exe ./cmd/cosine-cli

echo Using existing data directories...
echo Using existing configuration files...

echo Starting Node 1...
start "COSINE Node 1" cmd /c "cosine-cli.exe -config configs/config-node1.yaml"

echo Waiting for Node 1 to initialize (5 seconds)...
timeout /t 5

echo Starting Node 2...
start "COSINE Node 2" cmd /c "cosine-cli.exe -config configs/config-node2.yaml"

echo Waiting for Node 2 to initialize (5 seconds)...
timeout /t 5

echo Starting Node 3...
start "COSINE Node 3" cmd /c "cosine-cli.exe -config configs/config-node3.yaml"

echo All nodes started. Check the terminal windows for logs.
