peerRegistry:
  path: "data/peer_registry.json"

p2p:
  port: 9001
  maxPeers: 50
  pingInterval: "30s"
  discoveryInterval: "1m"
  bootstrapNodes: [] # Will be populated from registry

node:
  id: "node-1"
  environment: "development"
  datadir: "data/node1"

logging:
  level: "debug"
  outputs:
    - "stdout"
    - "logs/cosine-node1.log"
  encoding: "console"

metrics:
  enabled: true
  address: ":9091"
  path: "/metrics"

api:
  enabled: true
  port: 8081
