# General node configuration
node:
  id: "test-node-1"
  environment: "development"
  datadir: "./data"

# Logging configuration
logging:
  level: "debug"
  outputs: ["stdout", "./logs/cosine.log"]
  encoding: "console"
  rotate:
    maxSize: 100
    maxBackups: 5
    maxAge: 30
    compress: true

# Metrics configuration
metrics:
  enabled: true
  address: ":9090"
  path: "/metrics"

# Consensus parameters
consensus:
  alpha: 0.5
  beta: 0.2
  gamma: 0.1
  maxValidators: 100

# Credit scoring parameters
creditscore:
  kalman:
    tau_initial: 2.5
    k_initial: 3.0
    p_initial: 1.0
    q_tau: 0.01
    q_k: 0.01
    r_tau: 1.0
    r_k: 1.0
  
  scaling:
    k_neg_initial: 1.0
    k_pos_initial: 1.0
    k_assoc_initial: 1.0
    k_rehab_initial: 1.0
    q: 0.01
    r: 1.0

# Fraud detection parameters
fraud:
  timeWindow:
    min: "30d"
    max: "730d"
  hopLimit:
    min: 1
    max: 15
  association:
    beta: 0.5
    delta: 0.01

# Voting and governance
voting:
  newWalletReputation: 0.1
  alpha: 0.05
  beta: 0.1
  lambda: 2.5

# Reward parameters
rewards:
  per_validator: 0.01
  association: 0.05
  rehabilitation: 0.03

# Fee parameters
fees:
  verification:
    kappa: 1.2
  token:
    baseFee: 0.002